# Generated by Django 3.2.25 on 2024-06-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20240621_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_change_books_data', 'Add, edit, delete books'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name_ml',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name_ml',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'На оформлении'), ('o', 'Выдана'), ('a', 'Доступна'), ('r', 'В резерве')], default='d', help_text='Статус доступности книги', max_length=1, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Жанр книги. Например, Фантастика, Детектив, Поэзия и т.п.', max_length=200, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Язык издания книги. Например, Русский, English, 中國 и т.п.', max_length=200, unique=True, verbose_name='Наименование'),
        ),
    ]
